import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.UnsupportedLookAndFeelException;

class Main extends JFrame {

  private static final String CONN = "jdbc:mysql://176.96.239.141:3306/u2864_skillbox2?useSSL=false";
  private static final String USER = "u2864_skillbox2";
  private static final String PASS = "9S7j1D0b";

  TodoClass todoClass = new TodoClass();

  public Main() {
    initComponents();
    todoClass.getCreateTable();
    initComponents();
    Toolkit toolkit = Toolkit.getDefaultToolkit();
    Dimension screenSize = toolkit.getScreenSize();
    JFrame frame = new JFrame("Demo");
    frame.setSize(550, 600);
    //Calculate the frame location
    int x = (screenSize.width - frame.getWidth()) / 2;
    int y = (screenSize.height - frame.getHeight()) / 2;
    //Set the new frame location
    frame.setLocation(x, y);
    setLocation(x, y);
    list();
    super.setTitle("Список дел на Java");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jTextField1 = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(0, 128, 128));

    jPanel1.setBackground(new java.awt.Color(0, 128, 128));

    jLabel1.setFont(new java.awt.Font("Tahoma", Font.BOLD, 14)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(240, 240, 240));
    jLabel1.setText("Вывод всех заметок:");
    jLabel1.setToolTipText("");

    jTextArea1.setEditable(false);
    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jTextArea1.setFocusable(false);
    jScrollPane1.setViewportView(jTextArea1);

    jButton1.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12)); // NOI18N
    jButton1.setText("Список всех дел");
    jButton1.setFocusable(false);
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
//        //    jButton1ActionPerformed(e);
//        //textfield.setText(null); //or use this
//      }
      }
    });

    //    jButton3.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12)); // NOI18N
//    jButton3.setText("Очистка");
//    jButton3.addActionListener(new ActionListener() {
//      public void actionPerformed(ActionEvent e) {
//        jTextArea1.setText("");
//        //    jButton1ActionPerformed(e);
//        //textfield.setText(null); //or use this
//      }
//    });
//
//    jButton4.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12)); // NOI18N
//    jButton4.setText("Список команд");
//    jButton4.addActionListener(new java.awt.event.ActionListener() {
//      public void actionPerformed(java.awt.event.ActionEvent evt) {
//        jButton4ActionPerformed(evt);
//        //    jButton1ActionPerformed(e);
//        //textfield.setText(null); //or use this
//      }
//    });

    jButton2.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12)); // NOI18N
    jButton2.setText("Очистка");
    jButton2.setFocusable(false);

    jButton3.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12)); // NOI18N
    jButton3.setText("Список команд");
    jButton3.setFocusable(false);
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });

    jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jButton4.setText("Отправить");
    jButton4.setFocusable(false);

    Action action = new AbstractAction()
    {
      @Override
      public void actionPerformed(ActionEvent e) {
        jTextField1.getText();
        try {
          if (jTextField1.getText().equals("")) {
            System.err.println("Should not be NULL");
          }
          String inputLine = jTextField1.getText();
          if (!jTextField1.getText().equals("")) {

            if (inputLine.matches(todoClass.COMMAND_ADD_TO_INDEX)) {
              todoClass.addToIndex(inputLine);
              list();
              jTextField1.setText("");
            }
            if (inputLine.matches(todoClass.ALL_LETTERS_AND_NUMBERS)) {
              todoClass.addText(inputLine);
              list();
              jTextField1.setText("");
            } else if (inputLine.matches(todoClass.COMMAND_ADD_TO_INDEX_RU)) {
              todoClass.addToIndex(inputLine);
              list();
            } else if (inputLine.matches(todoClass.COMMAND_ADD)) {
              todoClass.add(inputLine);
              list();
              jTextField1.setText("");
            } else if (inputLine.matches(todoClass.COMMAND_ADD_RU)) {
              todoClass.add(inputLine);
              list();
              jTextField1.setText("");
            } else if (inputLine.matches(todoClass.COMMAND_DELETE_ALL_RU)) {
              todoClass.deleteAll(inputLine);
              list();
              jTextField1.setText("");
            } else if (inputLine.matches(todoClass.COMMAND_DELETE_ALL)) {
              todoClass.deleteAll(inputLine);
              list();
              jTextField1.setText("");
            } else if (inputLine.matches(todoClass.COMMAND_EDIT)) {
              todoClass.editByIndex(inputLine);
              list();
              jTextField1.setText("");
            } else if (inputLine.matches(todoClass.COMMAND_DELETE)) {
              todoClass.deleteByIndex(inputLine);
              list();
              jTextField1.setText("");
            } else if (inputLine.matches(todoClass.COMMAND_DEL)) {
              todoClass.deleteByIndex(inputLine);
              list();
              jTextField1.setText("");
            } else if (inputLine.matches(todoClass.COMMAND_EDIT_RU)) {
              todoClass.editByIndex(inputLine);
              list();
              jTextField1.setText("");
            } else if (inputLine.matches(todoClass.COMMAND_DELETE_RU)) {
              todoClass.deleteByIndex(inputLine);
              list();
              jTextField1.setText("");
            } else if (inputLine.matches(todoClass.COMMAND_DELETE_BD)) {
              todoClass.getDropTable();
              list();
              jTextField1.setText("");
            }
            else {
              jTextArea1.setText("Скорее всего произошла ошибка." + "\n" + "Вы написали все с маленькой бувы");
            }
          }
        } catch (Exception ee) {
          ee.printStackTrace();
        }
      }
    };
    jTextField1.addActionListener(action);

    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        //  jButton3ActionPerformed(evt);
        //jTextArea1.add(input);
        try {
          if (jTextField1.getText().equals("")) {
            System.err.println("Should not be NULL");
          }
          String input = jTextField1.getText();
          if (!jTextField1.getText().equals("")) {
            if (input.matches(todoClass.COMMAND_ADD_TO_INDEX)) {
              todoClass.addToIndex(input);
              list();
              jTextField1.setText("");
            }
            if (input.matches(todoClass.ALL_LETTERS_AND_NUMBERS)) {
              todoClass.addText(input);
              list();
              jTextField1.setText("");
            } else if (input.matches(todoClass.COMMAND_ADD_TO_INDEX_RU)) {
              todoClass.addToIndex(input);
              list();
              jTextField1.setText("");
            } else if (input.matches(todoClass.COMMAND_ADD)) {
              todoClass.add(input);
              list();
              jTextField1.setText("");
            } else if (input.matches(todoClass.COMMAND_ADD_RU)) {
              todoClass.add(input);
              list();
              jTextField1.setText("");
            } else if (input.matches(todoClass.COMMAND_DELETE_ALL_RU)) {
              todoClass.deleteAll(input);
              list();
              jTextField1.setText("");
            } else if (input.matches(todoClass.COMMAND_DELETE_ALL)) {
              todoClass.deleteAll(input);
              list();
              jTextField1.setText("");
            } else if (input.matches(todoClass.COMMAND_EDIT)) {
              todoClass.editByIndex(input);
              list();
              jTextField1.setText("");
            } else if (input.matches(todoClass.COMMAND_DELETE)) {
              todoClass.deleteByIndex(input);
              list();
              jTextField1.setText("");
            } else if (input.matches(todoClass.COMMAND_DEL)) {
              todoClass.deleteByIndex(input);
              list();
              jTextField1.setText("");
            } else if (input.matches(todoClass.COMMAND_EDIT_RU)) {
              todoClass.editByIndex(input);
              list();
              jTextField1.setText("");
            } else if (input.matches(todoClass.COMMAND_DELETE_RU)) {
              todoClass.deleteByIndex(input);
              list();
              jTextField1.setText("");
            } else if (input.matches(todoClass.COMMAND_DELETE_BD)) {
              todoClass.getDropTable();
              list();
              jTextField1.setText("");
            } else {
              jTextArea1.setText("Произошла ошибка." + "\n" + "Вы написали все с маленькой буквы");
            }
          }
        } catch (Exception e) {
          e.printStackTrace();
        }
      }
    });

    jTextField1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField1ActionPerformed(evt);
      }
    });

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(240, 240, 240));
    jLabel2.setText("Поле ввода:");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 217, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(36, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>

  private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
    list();
  }

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  //  private void jButton2ActionPerformed(ActionEvent evt) {
//    //список дел
//    list();
//  }
//
//  private void jButton4ActionPerformed(ActionEvent evt) {
//    //список дел
//    availableCommands();
//  }

    public int num() {
    try {
      Class.forName("com.mysql.jdbc.Driver");
      Connection conn = DriverManager.getConnection(CONN, USER, PASS);
      Statement statement = conn.createStatement();
      ResultSet resultSet = statement.executeQuery("SELECT COUNT(id) AS id FROM Todolist");
      if (resultSet.next()) {
        return resultSet.getInt(1);
      }
    } catch (Exception ignored) {
    }
    return 0;
  }

  public void list() {
    jTextArea1.setText("");
    if (num() == 0) {
      jTextArea1.setText("Заметок нет!");
    } else {
      try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn = DriverManager.getConnection(CONN, USER, PASS);
        //Получаем данные и выводим
        Statement statement = conn.createStatement();
        String sql = "SELECT id, text, time FROM Todolist ORDER BY id ASC";
        ResultSet rs = statement.executeQuery(sql);
        //  jTextArea1.append("Список всех заметок: ");
        while (rs.next()) {
          String id = rs.getString("id");
          String text = rs.getString("text");
          String time = rs.getString("time");
          //Вывод данных
          // todoList.put(id, text);
          //jTextArea1.append("\n" + id + ". " + text + " | Дата создания: " + time);
          jTextArea1.append(id + ". " + text + " | Дата создания: " + time + "\n");
        }
        System.out.println();
        rs.close();
        conn.close();
      } catch (Exception e) {
        System.err.println(e.getMessage());
      }
    }
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String[] args) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException | InstantiationException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Main().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JTextField jTextField1;
  // End of variables declaration
}




















//  private javax.swing.JTextArea jTextArea1;
//
//  public TodoClass todoClass = new TodoClass();
//
//  public Main() {
//    todoClass.getCreateTable();
//    initComponents();
//    Toolkit toolkit = Toolkit.getDefaultToolkit();
//    Dimension screenSize = toolkit.getScreenSize();
//    JFrame frame = new JFrame("Demo");
//    frame.setSize(550, 600);
//    //Calculate the frame location
//    int x = (screenSize.width - frame.getWidth()) / 2;
//    int y = (screenSize.height - frame.getHeight()) / 2;
//    //Set the new frame location
//    frame.setLocation(x, y);
//    setLocation(x, y);
//    list();
//    super.setTitle("Список дел на Java");
//  }
//
//  private void initComponents() {
//
//    javax.swing.JButton jButton1 = new javax.swing.JButton();
//    JScrollPane jScrollPane1 = new JScrollPane();
//    jTextArea1 = new javax.swing.JTextArea();
//    javax.swing.JButton jButton2 = new javax.swing.JButton();
//    javax.swing.JButton jButton3 = new javax.swing.JButton();
//    javax.swing.JButton jButton4 = new javax.swing.JButton();
//    JScrollPane jScrollPane2 = new JScrollPane();
//    javax.swing.JTextPane jTextPane1 = new javax.swing.JTextPane();
//
//    JTextField jTextField1 = new JTextField();
//    JLabel jLabel1 = new JLabel();
//    JLabel jLabel2 = new JLabel();
//
//    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//    jTextArea1.setEditable(false);
//    jTextArea1.setColumns(20);
//    jTextArea1.setRows(5);
//    jScrollPane1.setViewportView(jTextArea1);
//
//    jButton1.setText("Отправить");
//
//    Action action = new AbstractAction()
//    {
//      @Override
//      public void actionPerformed(ActionEvent e) {
//        jTextField1.getText();
//        try {
//          if (jTextField1.getText().equals("")) {
//            System.err.println("Should not be NULL");
//          }
//          String inputLine = jTextField1.getText();
//          if (!jTextField1.getText().equals("")) {
//
//            if (inputLine.matches(todoClass.COMMAND_ADD_TO_INDEX)) {
//              todoClass.addToIndex(inputLine);
//              list();
//              jTextField1.setText("");
//            }
//            if (inputLine.matches(todoClass.ALL_LETTERS_AND_NUMBERS)) {
//              todoClass.addText(inputLine);
//              list();
//              jTextField1.setText("");
//            } else if (inputLine.matches(todoClass.COMMAND_ADD_TO_INDEX_RU)) {
//              todoClass.addToIndex(inputLine);
//              list();
//            } else if (inputLine.matches(todoClass.COMMAND_ADD)) {
//              todoClass.add(inputLine);
//              list();
//              jTextField1.setText("");
//            } else if (inputLine.matches(todoClass.COMMAND_ADD_RU)) {
//              todoClass.add(inputLine);
//              list();
//              jTextField1.setText("");
//            } else if (inputLine.matches(todoClass.COMMAND_DELETE_ALL_RU)) {
//              todoClass.deleteAll(inputLine);
//              list();
//              jTextField1.setText("");
//            } else if (inputLine.matches(todoClass.COMMAND_DELETE_ALL)) {
//              todoClass.deleteAll(inputLine);
//              list();
//              jTextField1.setText("");
//            } else if (inputLine.matches(todoClass.COMMAND_EDIT)) {
//              todoClass.editByIndex(inputLine);
//              list();
//              jTextField1.setText("");
//            } else if (inputLine.matches(todoClass.COMMAND_DELETE)) {
//              todoClass.deleteByIndex(inputLine);
//              list();
//              jTextField1.setText("");
//            } else if (inputLine.matches(todoClass.COMMAND_DEL)) {
//              todoClass.deleteByIndex(inputLine);
//              list();
//              jTextField1.setText("");
//            } else if (inputLine.matches(todoClass.COMMAND_EDIT_RU)) {
//              todoClass.editByIndex(inputLine);
//              list();
//              jTextField1.setText("");
//            } else if (inputLine.matches(todoClass.COMMAND_DELETE_RU)) {
//              todoClass.deleteByIndex(inputLine);
//              list();
//              jTextField1.setText("");
//            } else if (inputLine.matches(todoClass.COMMAND_DELETE_BD)) {
//              todoClass.getDropTable();
//              list();
//              jTextField1.setText("");
//            }
//            else {
//              jTextArea1.setText("Скорее всего произошла ошибка." + "\n" + "Вы написали все с маленькой бувы");
//            }
//          }
//        } catch (Exception ee) {
//          ee.printStackTrace();
//        }
//      }
//    };
//    jTextField1.addActionListener(action);
//
//    jButton1.addActionListener(new java.awt.event.ActionListener() {
//      public void actionPerformed(java.awt.event.ActionEvent evt) {
//        //  jButton3ActionPerformed(evt);
//        //jTextArea1.add(input);
//        try {
//          if (jTextField1.getText().equals("")) {
//            System.err.println("Should not be NULL");
//          }
//          String input = jTextField1.getText();
//          if (!jTextField1.getText().equals("")) {
//            if (input.matches(todoClass.COMMAND_ADD_TO_INDEX)) {
//              todoClass.addToIndex(input);
//              list();
//              jTextField1.setText("");
//            }
//            if (input.matches(todoClass.ALL_LETTERS_AND_NUMBERS)) {
//              todoClass.addText(input);
//              list();
//              jTextField1.setText("");
//            } else if (input.matches(todoClass.COMMAND_ADD_TO_INDEX_RU)) {
//              todoClass.addToIndex(input);
//              list();
//              jTextField1.setText("");
//            } else if (input.matches(todoClass.COMMAND_ADD)) {
//              todoClass.add(input);
//              list();
//              jTextField1.setText("");
//            } else if (input.matches(todoClass.COMMAND_ADD_RU)) {
//              todoClass.add(input);
//              list();
//              jTextField1.setText("");
//            } else if (input.matches(todoClass.COMMAND_DELETE_ALL_RU)) {
//              todoClass.deleteAll(input);
//              list();
//              jTextField1.setText("");
//            } else if (input.matches(todoClass.COMMAND_DELETE_ALL)) {
//              todoClass.deleteAll(input);
//              list();
//              jTextField1.setText("");
//            } else if (input.matches(todoClass.COMMAND_EDIT)) {
//              todoClass.editByIndex(input);
//              list();
//              jTextField1.setText("");
//            } else if (input.matches(todoClass.COMMAND_DELETE)) {
//              todoClass.deleteByIndex(input);
//              list();
//              jTextField1.setText("");
//            } else if (input.matches(todoClass.COMMAND_DEL)) {
//              todoClass.deleteByIndex(input);
//              list();
//              jTextField1.setText("");
//            } else if (input.matches(todoClass.COMMAND_EDIT_RU)) {
//              todoClass.editByIndex(input);
//              list();
//              jTextField1.setText("");
//            } else if (input.matches(todoClass.COMMAND_DELETE_RU)) {
//              todoClass.deleteByIndex(input);
//              list();
//              jTextField1.setText("");
//            } else if (input.matches(todoClass.COMMAND_DELETE_BD)) {
//              todoClass.getDropTable();
//              list();
//              jTextField1.setText("");
//            } else {
//              jTextArea1.setText("Произошла ошибка." + "\n" + "Вы написали все с маленькой буквы");
//            }
//          }
//        } catch (Exception e) {
//          e.printStackTrace();
//        }
//      }
//    });
//
//    jButton2.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12)); // NOI18N
//    jButton2.setText("Список всех дел");
//    jButton2.addActionListener(new java.awt.event.ActionListener() {
//      public void actionPerformed(java.awt.event.ActionEvent evt) {
//        jButton2ActionPerformed(evt);
//      }
//    });
//
//    jButton3.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12)); // NOI18N
//    jButton3.setText("Очистка");
//    jButton3.addActionListener(new ActionListener() {
//      public void actionPerformed(ActionEvent e) {
//        jTextArea1.setText("");
//        //    jButton1ActionPerformed(e);
//        //textfield.setText(null); //or use this
//      }
//    });
//
//    jButton4.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12)); // NOI18N
//    jButton4.setText("Список команд");
//    jButton4.addActionListener(new java.awt.event.ActionListener() {
//      public void actionPerformed(java.awt.event.ActionEvent evt) {
//        jButton4ActionPerformed(evt);
//        //    jButton1ActionPerformed(e);
//        //textfield.setText(null); //or use this
//      }
//    });
//
//
//    // jTextPane1.setToolTipText("");
//    jScrollPane2.setViewportView(jTextPane1);
//
//    jLabel1.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 14)); // NOI18N
//    jLabel1.setText("Вывод всех заметок:");
//
//    jLabel2.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 14)); // NOI18N
//    jLabel2.setText("Поле ввода:");
//
//    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//    getContentPane().setLayout(layout);
//    layout.setHorizontalGroup(
//        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(jScrollPane1)
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(jTextField1)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButton1))
//                    .addGroup(layout.createSequentialGroup()
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addGroup(layout.createSequentialGroup()
//                                .addComponent(jButton2)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addComponent(jButton3)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addComponent(jButton4)))
//                        .addGap(0, 217, Short.MAX_VALUE)))
//                .addContainerGap())
//    );
//    layout.setVerticalGroup(
//        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(jLabel1)
//                .addGap(4, 4, 4)
//                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jButton2)
//                    .addComponent(jButton3)
//                    .addComponent(jButton4))
//                .addGap(7, 7, 7)
//                .addComponent(jLabel2)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jButton1))
//                .addContainerGap(48, Short.MAX_VALUE))
//    );
//
//    pack();
//  }// </editor-fold>
//
////  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
////    // отправить
////
////  }
//
//  private void jButton2ActionPerformed(ActionEvent evt) {
//    //список дел
//    list();
//  }
//
//  private void jButton4ActionPerformed(ActionEvent evt) {
//    //список дел
//    availableCommands();
//  }
//
////  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
////    // очистка
////
////  }
//
//  public void availableCommands() {
//    jTextArea1.setText("");
//    jTextArea1.setText("Доступные команды:"
//        + "\nadd, "
//        + "add Index, "
//        + "edit Index, "
//        + "delete index, "
//        + "del index, "
//        + "delete all, "
//        + "list"
//        + "\nадд, "
//        + "адд индекс, "
//        + "изменить индекс, "
//        + "удалить индекс, "
//        + "удалить все, "
//        + "лист"
//        + "\nP. S. Index/индекс = цифра"
//        + "\nP. S.2 Если слово начинается с большой буквы, то комманду писать не нужно!");
//  }
//
//  public int num() {
//    try {
//      Class.forName("com.mysql.jdbc.Driver");
//      Connection conn = DriverManager.getConnection(CONN, USER, PASS);
//      Statement statement = conn.createStatement();
//      ResultSet resultSet = statement.executeQuery("SELECT COUNT(id) AS id FROM Todolist");
//      if (resultSet.next()) {
//        return resultSet.getInt(1);
//      }
//    } catch (Exception ignored) {
//    }
//    return 0;
//  }
//
//  public void list() {
//    jTextArea1.setText("");
//    if (num() == 0) {
//      jTextArea1.setText("Заметок нет!");
//    } else {
//      try {
//        Class.forName("com.mysql.jdbc.Driver");
//        Connection conn = DriverManager.getConnection(CONN, USER, PASS);
//        //Получаем данные и выводим
//        Statement statement = conn.createStatement();
//        String sql = "SELECT id, text, time FROM Todolist ORDER BY id ASC";
//        ResultSet rs = statement.executeQuery(sql);
//        //  jTextArea1.append("Список всех заметок: ");
//        while (rs.next()) {
//          String id = rs.getString("id");
//          String text = rs.getString("text");
//          String time = rs.getString("time");
//          //Вывод данных
//          // todoList.put(id, text);
//          //jTextArea1.append("\n" + id + ". " + text + " | Дата создания: " + time);
//          jTextArea1.append(id + ". " + text + " | Дата создания: " + time + "\n");
//        }
//        System.out.println();
//        rs.close();
//        conn.close();
//      } catch (Exception e) {
//        System.err.println(e.getMessage());
//      }
//    }
//  }
//
//  public static void main(String[] args) {
//    try {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
//          .getInstalledLookAndFeels()) {
//        if ("Nimbus".equals(info.getName())) {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//        }
//      }
//    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
//      java.util.logging.Logger.getLogger(Main.class.getName())
//          .log(java.util.logging.Level.SEVERE, null, ex);
//    }
//
//    java.awt.EventQueue.invokeLater(new Runnable() {
//      public void run() {
//        new Main().setVisible(true);
//      }
//    });
//  }
